-- Funnel opt-in Masterclass : suivi interne pseudonyme, sans email ni téléphone.
-- Écriture et lecture uniquement via les Netlify Functions (service role).

create table if not exists public.masterclass_optin_events (
  id bigint generated by default as identity primary key,
  funnel_id uuid not null,
  event_name text not null check (
    event_name in (
      'page_view',
      'popup_opened',
      'step_1_completed',
      'step_2_completed',
      'registration_completed'
    )
  ),
  variant text not null default 'v2',
  path text not null default '/masterclass/',
  traffic_source text,
  country_code text,
  selected_country text,
  session_date timestamptz,
  created_at timestamptz not null default now(),
  constraint masterclass_optin_events_once_per_step unique (funnel_id, event_name)
);

create index if not exists masterclass_optin_events_created_at_idx
  on public.masterclass_optin_events (created_at desc);

create index if not exists masterclass_optin_events_variant_session_idx
  on public.masterclass_optin_events (variant, session_date, created_at desc);

comment on table public.masterclass_optin_events is
  'Événements pseudonymes du funnel /masterclass/ ; aucune donnée de contact.';

alter table public.masterclass_optin_events enable row level security;

-- Aucune policy : anon/authenticated n’accèdent pas ; la service role Netlify bypass RLS.
