-- Confirmation contractuelle MC2 figée après paiement initial confirmé.
-- Migration additive et idempotente à exécuter manuellement dans Supabase.

create table if not exists public.mc2_contract_documents (
  id bigint generated by default as identity primary key,
  registration_token text not null references public.mc2_registrations(token) on delete restrict,
  access_token text not null,
  access_token_hash text not null,
  document_reference text not null,
  product_key text not null check (product_key = 'esprit-subconscient-2'),
  source_stripe_event_id text not null,
  purchased_at timestamptz not null,
  snapshot jsonb not null,
  rendered_html text not null,
  notification_status text not null default 'pending'
    check (notification_status in ('pending', 'processing', 'retry', 'delivered', 'skipped')),
  notification_due_at timestamptz not null default now(),
  notification_attempts integer not null default 0 check (notification_attempts >= 0),
  notification_last_attempt_at timestamptz,
  notification_last_error text,
  notification_delivered_at timestamptz,
  mailerlite_group_id text,
  mailerlite_subscriber_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (registration_token),
  unique (access_token_hash),
  unique (document_reference)
);

create index if not exists idx_mc2_contract_documents_notification
  on public.mc2_contract_documents (notification_status, notification_due_at)
  where notification_status in ('pending', 'retry');

create index if not exists idx_mc2_contract_documents_purchase
  on public.mc2_contract_documents (purchased_at desc);

create or replace function public.protect_mc2_contract_document_snapshot()
returns trigger
language plpgsql
as $$
begin
  if new.registration_token is distinct from old.registration_token
    or new.access_token is distinct from old.access_token
    or new.access_token_hash is distinct from old.access_token_hash
    or new.document_reference is distinct from old.document_reference
    or new.product_key is distinct from old.product_key
    or new.source_stripe_event_id is distinct from old.source_stripe_event_id
    or new.purchased_at is distinct from old.purchased_at
    or new.snapshot is distinct from old.snapshot
    or new.rendered_html is distinct from old.rendered_html then
    raise exception 'MC2 contract document snapshots are immutable';
  end if;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_protect_mc2_contract_document_snapshot on public.mc2_contract_documents;
create trigger tr_protect_mc2_contract_document_snapshot
  before update on public.mc2_contract_documents
  for each row execute function public.protect_mc2_contract_document_snapshot();

alter table public.mc2_contract_documents enable row level security;

comment on table public.mc2_contract_documents is
  'Copie contractuelle MC2 immuable créée uniquement après paiement initial Stripe confirmé; aucun accès anon/authenticated.';
comment on column public.mc2_contract_documents.access_token is
  'Secret bearer opaque utilisé uniquement pour construire le lien client; ne jamais journaliser ni exposer dans une API JSON.';
comment on column public.mc2_contract_documents.access_token_hash is
  'SHA-256 du secret opaque utilisé pour la recherche à temps constant côté fonction.';
comment on column public.mc2_contract_documents.snapshot is
  'Prix, échéancier, vendeur et CGV figés au moment du webhook paid; protégés contre toute mise à jour.';
comment on column public.mc2_contract_documents.rendered_html is
  'Copie HTML autonome figée au même instant que le snapshot et servie sans recalcul depuis une offre mutable.';
