-- Prérequis additif pour la réinscription MC2. À exécuter par Sonny.
-- N'active PAS la réinscription, ne modifie aucune inscription/exclusion,
-- ne programme et n'envoie aucun email/SMS. Réexécutable.
begin;

create table if not exists public.mc2_registration_history (
  id bigint generated by default as identity primary key,
  registration_id bigint not null,
  token text not null,
  session_starts_at timestamptz not null,
  archived_at timestamptz not null default now(),
  reason text not null check (reason = 'reregistration'),
  snapshot jsonb not null check (jsonb_typeof(snapshot) = 'object'),
  unique (token, session_starts_at)
);

create index if not exists mc2_registration_history_registration_idx
  on public.mc2_registration_history (registration_id, archived_at);

alter table public.mc2_registration_history enable row level security;
revoke all on public.mc2_registration_history from public, anon, authenticated;
grant select, insert on public.mc2_registration_history to service_role;
revoke update, delete, truncate on public.mc2_registration_history from service_role;
grant usage, select on sequence public.mc2_registration_history_id_seq to service_role;

comment on table public.mc2_registration_history is
  'Archives privées des tentatives MC2 avant réinscription. Aucun accès navigateur. Ne pas supprimer les événements de tracking liés au token.';

commit;

-- Contrôle final : doit retourner true.
select to_regclass('public.mc2_registration_history') is not null as history_ready;
