-- Recuperation comportementale MC2 (replay + offre).
-- Migration idempotente et isolee : aucune modification des tables historiques.
-- A executer manuellement dans Supabase avant d'activer MC2_REPLAY_RECOVERY_ENABLED.

create table if not exists public.mc2_replay_recovery_jobs (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token),
  job_key text not null unique,
  session_starts_at timestamptz not null,
  segment text not null
    check (segment in ('no_show', 'left_before_cta', 'offer_seen_no_purchase')),
  due_at timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'delivered', 'skipped', 'cancelled')),
  attempts integer not null default 0 check (attempts >= 0),
  access_code text unique,
  access_starts_at timestamptz,
  access_expires_at timestamptz,
  resume_seconds integer not null default 0 check (resume_seconds >= 0),
  mailerlite_group_id text,
  mailerlite_subscriber_id text,
  last_error text,
  skip_reason text,
  last_attempt_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Rend la migration réexécutable même si une première version de la table a
-- déjà été créée pendant les tests d'intégration.
alter table public.mc2_replay_recovery_jobs
  add column if not exists token text,
  add column if not exists job_key text,
  add column if not exists session_starts_at timestamptz,
  add column if not exists segment text,
  add column if not exists due_at timestamptz,
  add column if not exists status text not null default 'pending',
  add column if not exists attempts integer not null default 0,
  add column if not exists access_code text,
  add column if not exists access_starts_at timestamptz,
  add column if not exists access_expires_at timestamptz,
  add column if not exists resume_seconds integer not null default 0,
  add column if not exists mailerlite_group_id text,
  add column if not exists mailerlite_subscriber_id text,
  add column if not exists last_error text,
  add column if not exists skip_reason text,
  add column if not exists last_attempt_at timestamptz,
  add column if not exists delivered_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists uq_mc2_replay_recovery_job_key
  on public.mc2_replay_recovery_jobs (job_key);

create unique index if not exists uq_mc2_replay_recovery_access_code
  on public.mc2_replay_recovery_jobs (access_code)
  where access_code is not null;

create index if not exists idx_mc2_replay_recovery_due
  on public.mc2_replay_recovery_jobs (status, due_at)
  where status in ('pending', 'retry');

create index if not exists idx_mc2_replay_recovery_token
  on public.mc2_replay_recovery_jobs (token, created_at desc);

create index if not exists idx_mc2_replay_recovery_access
  on public.mc2_replay_recovery_jobs (access_code, access_expires_at)
  where access_code is not null and status = 'delivered';

create or replace function public.set_mc2_replay_recovery_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_mc2_replay_recovery_updated_at
  on public.mc2_replay_recovery_jobs;
create trigger tr_mc2_replay_recovery_updated_at
  before update on public.mc2_replay_recovery_jobs
  for each row execute function public.set_mc2_replay_recovery_updated_at();

alter table public.mc2_replay_recovery_jobs enable row level security;

comment on table public.mc2_replay_recovery_jobs is
  'File idempotente et privee de recuperation MC2. Desactivee tant que MC2_REPLAY_RECOVERY_ENABLED=false.';
