-- File d'onboarding Circle pour les achats confirmés du nouveau funnel MC2.
-- Aucun membre Circle et aucun tag existant ne sont supprimés par ce schéma.

create table if not exists public.mc2_circle_onboarding_jobs (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token),
  job_key text not null unique,
  email text not null,
  member_name text,
  member_tag_name text not null default 'ES 2.0 (AVANCÉ)'
    check (member_tag_name = 'ES 2.0 (AVANCÉ)'),
  stripe_event_id text,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'succeeded', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz default now(),
  last_attempt_at timestamptz,
  circle_member_id text,
  circle_member_tag_id text,
  member_created boolean not null default false,
  tag_added boolean not null default false,
  provider_response jsonb not null default '{}'::jsonb,
  last_error text,
  succeeded_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_mc2_circle_onboarding_due
  on public.mc2_circle_onboarding_jobs (status, next_attempt_at)
  where status in ('pending', 'retry');

create index if not exists idx_mc2_circle_onboarding_token
  on public.mc2_circle_onboarding_jobs (token, created_at desc);

create or replace function public.set_mc2_circle_onboarding_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_mc2_circle_onboarding_updated_at
  on public.mc2_circle_onboarding_jobs;
create trigger tr_mc2_circle_onboarding_updated_at
  before update on public.mc2_circle_onboarding_jobs
  for each row execute function public.set_mc2_circle_onboarding_updated_at();

alter table public.mc2_circle_onboarding_jobs enable row level security;

comment on table public.mc2_circle_onboarding_jobs is
  'File idempotente et journalisée: achat MC2 payé vers invitation Circle et ajout du tag ES 2.0 (AVANCÉ).';
