-- Emails de confirmation et rappel de session MC2.
-- Migration idempotente à exécuter manuellement dans Supabase.
create table if not exists public.mc2_session_email_jobs (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token) on delete cascade,
  job_key text not null unique,
  message_type text not null check (message_type in ('registration_confirmation', 'session_reminder_1h')),
  session_starts_at timestamptz not null,
  due_at timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'delivered', 'skipped', 'cancelled')),
  attempts integer not null default 0 check (attempts >= 0),
  mailerlite_group_id text,
  mailerlite_subscriber_id text,
  last_error text,
  skip_reason text,
  last_attempt_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.mc2_session_email_jobs
  add column if not exists token text,
  add column if not exists job_key text,
  add column if not exists message_type text,
  add column if not exists session_starts_at timestamptz,
  add column if not exists due_at timestamptz,
  add column if not exists status text not null default 'pending',
  add column if not exists attempts integer not null default 0,
  add column if not exists mailerlite_group_id text,
  add column if not exists mailerlite_subscriber_id text,
  add column if not exists last_error text,
  add column if not exists skip_reason text,
  add column if not exists last_attempt_at timestamptz,
  add column if not exists delivered_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
create unique index if not exists uq_mc2_session_email_job_key on public.mc2_session_email_jobs (job_key);
create index if not exists idx_mc2_session_email_jobs_due on public.mc2_session_email_jobs (status, due_at)
  where status in ('pending', 'retry');
create index if not exists idx_mc2_session_email_jobs_token on public.mc2_session_email_jobs (token, created_at desc);
create or replace function public.set_mc2_session_email_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists tr_mc2_session_email_updated_at on public.mc2_session_email_jobs;
create trigger tr_mc2_session_email_updated_at before update on public.mc2_session_email_jobs
  for each row execute function public.set_mc2_session_email_updated_at();
alter table public.mc2_session_email_jobs enable row level security;
comment on table public.mc2_session_email_jobs is
  'File idempotente des emails MC2 confirmation et rappel H-1.';
