-- File SMS transactionnelle du funnel MC2.
-- A exécuter une fois dans l'éditeur SQL Supabase avant d'activer MC2_SMS_ENABLED.

alter table public.mc2_registrations
  add column if not exists sms_consent_at timestamptz,
  add column if not exists sms_consent_source text;

create table if not exists public.mc2_sms_jobs (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token) on delete cascade,
  job_key text not null unique,
  message_type text not null
    check (message_type in ('session_live', 'offer_deadline')),
  due_at timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'sent', 'skipped')),
  attempts integer not null default 0,
  provider_message_id text,
  provider_status text,
  provider_response jsonb not null default '{}'::jsonb,
  last_error text,
  skip_reason text,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.mc2_sms_jobs
  add column if not exists live_code varchar(5);

create unique index if not exists idx_mc2_sms_jobs_live_code
  on public.mc2_sms_jobs (live_code)
  where live_code is not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'mc2_sms_jobs_live_code_format'
      and conrelid = 'public.mc2_sms_jobs'::regclass
  ) then
    alter table public.mc2_sms_jobs
      add constraint mc2_sms_jobs_live_code_format
      check (live_code is null or live_code ~ '^[A-Za-z0-9]{5}$');
  end if;
end;
$$;

create index if not exists idx_mc2_sms_jobs_due
  on public.mc2_sms_jobs (status, due_at)
  where status in ('pending', 'retry');

create index if not exists idx_mc2_sms_jobs_token
  on public.mc2_sms_jobs (token, created_at desc);

create or replace function public.set_mc2_sms_jobs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_mc2_sms_jobs_updated_at on public.mc2_sms_jobs;
create trigger tr_mc2_sms_jobs_updated_at
  before update on public.mc2_sms_jobs
  for each row execute function public.set_mc2_sms_jobs_updated_at();

alter table public.mc2_sms_jobs enable row level security;

comment on table public.mc2_sms_jobs is
  'File idempotente des SMS GatewayAPI du funnel MC2.';
