-- Dossiers de recouvrement MC2, préparés après les cinq reprises Stripe.
-- Migration additive et réexécutable. À exécuter manuellement par Sonny.
-- Aucun dossier n'est transmis à un prestataire par cette migration.

alter table public.mc2_registrations
  add column if not exists billing_full_name text,
  add column if not exists billing_phone text,
  add column if not exists billing_street text,
  add column if not exists billing_street2 text,
  add column if not exists billing_zip text,
  add column if not exists billing_city text,
  add column if not exists billing_country text,
  add column if not exists billing_completed_at timestamptz;

create table if not exists public.mc2_contract_acceptances (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token) on delete restrict,
  stripe_checkout_session_id text not null,
  contract_version text not null,
  terms_url text not null,
  terms_snapshot_url text,
  terms_snapshot_sha256 text,
  acceptance_text text not null,
  payment_plan text not null,
  payment_schedule jsonb not null default '[]'::jsonb,
  initial_payment_cents integer not null check (initial_payment_cents >= 0),
  contractual_total_cents integer not null check (contractual_total_cents >= 0),
  currency text not null default 'eur',
  accepted_at timestamptz not null,
  client_ip text,
  client_user_agent text,
  request_id text,
  evidence_sha256 text not null,
  created_at timestamptz not null default now(),
  unique (stripe_checkout_session_id, contract_version)
);

create index if not exists idx_mc2_contract_acceptances_token
  on public.mc2_contract_acceptances (token, accepted_at desc);

alter table public.mc2_contract_acceptances
  add column if not exists payment_schedule jsonb not null default '[]'::jsonb,
  add column if not exists terms_snapshot_url text,
  add column if not exists terms_snapshot_sha256 text;

create table if not exists public.mc2_payment_attempts (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token) on delete restrict,
  stripe_event_id text not null unique,
  stripe_invoice_id text not null,
  stripe_payment_intent_id text,
  attempt_sequence integer not null check (attempt_sequence >= 1),
  retry_sequence integer not null check (retry_sequence >= 0),
  status text not null check (status in ('failed', 'action_required')),
  amount_due_cents integer not null default 0 check (amount_due_cents >= 0),
  currency text not null default 'eur',
  failure_code text,
  decline_code text,
  failure_message text,
  next_retry_at timestamptz,
  occurred_at timestamptz not null,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_mc2_payment_attempts_invoice
  on public.mc2_payment_attempts (stripe_invoice_id, attempt_sequence);

create index if not exists idx_mc2_payment_attempts_token
  on public.mc2_payment_attempts (token, occurred_at desc);

create table if not exists public.mc2_collection_case_jobs (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token) on delete restrict,
  stripe_invoice_id text not null,
  source_stripe_event_id text,
  job_key text not null unique,
  retry_count integer not null check (retry_count = 5),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'completed', 'skipped', 'failed')),
  due_at timestamptz not null default now(),
  attempts integer not null default 0 check (attempts >= 0),
  last_attempt_at timestamptz,
  last_error text,
  skip_reason text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_mc2_collection_case_jobs_due
  on public.mc2_collection_case_jobs (status, due_at)
  where status in ('pending', 'retry');

create table if not exists public.mc2_collection_cases (
  id bigint generated by default as identity primary key,
  case_number text not null unique,
  token text not null references public.mc2_registrations(token) on delete restrict,
  stripe_invoice_id text not null unique,
  stripe_customer_id text,
  stripe_subscription_id text,
  status text not null default 'draft'
    check (status in (
      'draft', 'needs_information', 'ready_for_review', 'approved',
      'rejected', 'exported', 'recovered', 'closed'
    )),
  revision integer not null default 1 check (revision >= 1),
  currency text not null default 'eur',
  contractual_total_cents integer not null default 0 check (contractual_total_cents >= 0),
  paid_total_cents integer not null default 0 check (paid_total_cents >= 0),
  balance_due_cents integer not null default 0 check (balance_due_cents >= 0),
  overdue_invoice_cents integer not null default 0 check (overdue_invoice_cents >= 0),
  automatic_retry_count integer not null check (automatic_retry_count = 5),
  completeness jsonb not null default '{}'::jsonb,
  snapshot jsonb not null,
  snapshot_sha256 text not null,
  prepared_at timestamptz not null,
  ready_for_review_at timestamptz,
  approved_at timestamptz,
  approved_by text,
  rejected_at timestamptz,
  rejected_by text,
  rejection_reason text,
  exported_at timestamptz,
  exported_by text,
  provider_name text,
  provider_reference text,
  recovered_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_mc2_collection_cases_status
  on public.mc2_collection_cases (status, prepared_at desc);

create index if not exists idx_mc2_collection_cases_token
  on public.mc2_collection_cases (token, prepared_at desc);

create table if not exists public.mc2_collection_case_revisions (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.mc2_collection_cases(id) on delete restrict,
  revision integer not null check (revision >= 1),
  snapshot jsonb not null,
  snapshot_sha256 text not null,
  completeness jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (case_id, revision)
);

create table if not exists public.mc2_collection_case_audit (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.mc2_collection_cases(id) on delete restrict,
  event_type text not null,
  actor_type text not null default 'system'
    check (actor_type in ('system', 'human', 'export')),
  actor_id text,
  payload jsonb not null default '{}'::jsonb,
  event_sha256 text not null,
  occurred_at timestamptz not null default now()
);

create index if not exists idx_mc2_collection_case_audit_case
  on public.mc2_collection_case_audit (case_id, occurred_at, id);

create unique index if not exists idx_mc2_collection_case_audit_event
  on public.mc2_collection_case_audit (case_id, event_sha256);

-- Décision humaine et audit dans une seule transaction. La fonction n'est
-- exécutable que par la service role utilisée côté serveur.
create or replace function public.review_mc2_collection_case(
  p_case_id bigint,
  p_action text,
  p_expected_status text,
  p_actor_id text,
  p_reason text,
  p_event_sha256 text
)
returns public.mc2_collection_cases
language plpgsql
security definer
set search_path = public
as $$
declare
  current_case public.mc2_collection_cases;
  reviewed_case public.mc2_collection_cases;
  review_time timestamptz := now();
begin
  select * into current_case
  from public.mc2_collection_cases
  where id = p_case_id
  for update;

  if current_case.id is null then
    raise exception 'collection_case_not_found';
  end if;
  if current_case.status <> p_expected_status then
    raise exception 'collection_case_status_changed';
  end if;
  if p_action = 'approve' then
    if current_case.status <> 'ready_for_review'
       or coalesce((current_case.completeness ->> 'complete')::boolean, false) is not true then
      raise exception 'collection_case_not_ready';
    end if;
    update public.mc2_collection_cases
    set status = 'approved',
        approved_at = review_time,
        approved_by = p_actor_id,
        rejected_at = null,
        rejected_by = null,
        rejection_reason = null
    where id = p_case_id
    returning * into reviewed_case;
  elsif p_action = 'reject' then
    if current_case.status not in ('ready_for_review', 'needs_information') then
      raise exception 'collection_case_not_reviewable';
    end if;
    update public.mc2_collection_cases
    set status = 'rejected',
        rejected_at = review_time,
        rejected_by = p_actor_id,
        rejection_reason = coalesce(nullif(p_reason, ''), 'Rejet manuel')
    where id = p_case_id
    returning * into reviewed_case;
  else
    raise exception 'collection_case_action_invalid';
  end if;

  insert into public.mc2_collection_case_audit (
    case_id, event_type, actor_type, actor_id, payload, event_sha256, occurred_at
  ) values (
    p_case_id,
    case when p_action = 'approve' then 'human_approved' else 'human_rejected' end,
    'human',
    p_actor_id,
    jsonb_build_object(
      'action', p_action,
      'from_status', current_case.status,
      'to_status', reviewed_case.status,
      'revision', current_case.revision,
      'reason', p_reason
    ),
    p_event_sha256,
    review_time
  ) on conflict (case_id, event_sha256) do nothing;

  return reviewed_case;
end;
$$;

revoke all on function public.review_mc2_collection_case(bigint, text, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.review_mc2_collection_case(bigint, text, text, text, text, text)
  to service_role;

create or replace function public.set_mc2_collection_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_mc2_collection_jobs_updated_at
  on public.mc2_collection_case_jobs;
create trigger tr_mc2_collection_jobs_updated_at
  before update on public.mc2_collection_case_jobs
  for each row execute function public.set_mc2_collection_updated_at();

drop trigger if exists tr_mc2_collection_cases_updated_at
  on public.mc2_collection_cases;
create trigger tr_mc2_collection_cases_updated_at
  before update on public.mc2_collection_cases
  for each row execute function public.set_mc2_collection_updated_at();

create or replace function public.prevent_mc2_evidence_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'MC2 evidence rows are append-only';
end;
$$;

drop trigger if exists tr_mc2_contract_acceptances_immutable
  on public.mc2_contract_acceptances;
create trigger tr_mc2_contract_acceptances_immutable
  before update or delete on public.mc2_contract_acceptances
  for each row execute function public.prevent_mc2_evidence_mutation();

drop trigger if exists tr_mc2_payment_attempts_immutable
  on public.mc2_payment_attempts;
create trigger tr_mc2_payment_attempts_immutable
  before update or delete on public.mc2_payment_attempts
  for each row execute function public.prevent_mc2_evidence_mutation();

drop trigger if exists tr_mc2_collection_revisions_immutable
  on public.mc2_collection_case_revisions;
create trigger tr_mc2_collection_revisions_immutable
  before update or delete on public.mc2_collection_case_revisions
  for each row execute function public.prevent_mc2_evidence_mutation();

drop trigger if exists tr_mc2_collection_audit_immutable
  on public.mc2_collection_case_audit;
create trigger tr_mc2_collection_audit_immutable
  before update or delete on public.mc2_collection_case_audit
  for each row execute function public.prevent_mc2_evidence_mutation();

alter table public.mc2_contract_acceptances enable row level security;
alter table public.mc2_payment_attempts enable row level security;
alter table public.mc2_collection_case_jobs enable row level security;
alter table public.mc2_collection_cases enable row level security;
alter table public.mc2_collection_case_revisions enable row level security;
alter table public.mc2_collection_case_audit enable row level security;

comment on table public.mc2_contract_acceptances is
  'Preuve append-only de l’acceptation contractuelle MC2 au moment du paiement.';
comment on table public.mc2_payment_attempts is
  'Historique append-only de chaque tentative Stripe MC2 échouée.';
comment on table public.mc2_collection_cases is
  'Dossiers de recouvrement MC2 préparés sans transmission automatique.';
comment on table public.mc2_collection_case_revisions is
  'Versions immuables des dossiers de recouvrement MC2.';
comment on table public.mc2_collection_case_audit is
  'Journal immuable des décisions et exports des dossiers MC2.';
