-- Backend isolé du funnel MC2 just-in-time.
-- Ne modifie aucune table, fonction ou automatisation du webinaire bimensuel.

create table if not exists public.mc2_registrations (
  id bigint generated by default as identity primary key,
  token text not null unique,
  email text not null,
  prenom text not null,
  telephone text,
  pays text,
  session_slot_id text not null,
  slot_kind text not null check (slot_kind in ('jit', 'scheduled')),
  visitor_timezone text not null default 'UTC',
  session_starts_at timestamptz not null,
  session_ends_at timestamptz not null,
  offer_expires_at timestamptz,
  statut text not null default 'partial'
    check (statut in ('partial', 'registered', 'present', 'completed', 'purchased', 'expired')),
  traffic_source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  tt_click_id text,
  tt_event_id text,
  meta_fbc text,
  meta_fbp text,
  meta_event_id text,
  optin_variant text,
  optin_funnel_id text,
  registration_completed_at timestamptz,
  registered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_mc2_registrations_email_lower
  on public.mc2_registrations (lower(email));

create index if not exists idx_mc2_registrations_session
  on public.mc2_registrations (session_starts_at, statut);

create index if not exists idx_mc2_registrations_source
  on public.mc2_registrations (traffic_source, registered_at desc);

create or replace function public.set_mc2_registrations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_mc2_registrations_updated_at on public.mc2_registrations;
create trigger tr_mc2_registrations_updated_at
  before update on public.mc2_registrations
  for each row execute function public.set_mc2_registrations_updated_at();

alter table public.mc2_registrations enable row level security;

comment on table public.mc2_registrations is
  'Inscriptions isolées du funnel MC2 just-in-time; aucune dépendance au webinaire bimensuel.';

create table if not exists public.mc2_optin_events (
  id bigint generated by default as identity primary key,
  funnel_id text not null,
  event_name text not null,
  variant text not null default 'mc2',
  path text not null,
  traffic_source text,
  country_code text,
  selected_country text,
  session_date timestamptz,
  occurred_at timestamptz not null default now(),
  unique (funnel_id, event_name)
);

create index if not exists idx_mc2_optin_events_time
  on public.mc2_optin_events (occurred_at desc);

create index if not exists idx_mc2_optin_events_source
  on public.mc2_optin_events (traffic_source, event_name, occurred_at desc);

alter table public.mc2_optin_events enable row level security;

comment on table public.mc2_optin_events is
  'Étapes pré-inscription du funnel MC2; séparées des statistiques W2-W9.';

alter table public.mc2_registrations
  add column if not exists confirmation_view_count integer not null default 0,
  add column if not exists workbook_opened boolean not null default false,
  add column if not exists calendar_downloaded boolean not null default false,
  add column if not exists room_click_count integer not null default 0,
  add column if not exists session_page_view_count integer not null default 0,
  add column if not exists attended_live boolean not null default false,
  add column if not exists session_joined_at timestamptz,
  add column if not exists watch_first_second_live integer,
  add column if not exists watch_max_seconds_live integer not null default 0,
  add column if not exists watch_max_seconds_replay integer not null default 0,
  add column if not exists watch_max_minutes integer not null default 0,
  add column if not exists saw_offer boolean not null default false,
  add column if not exists clicked_cta boolean not null default false,
  add column if not exists cta_clicked_at timestamptz,
  add column if not exists visited_sales boolean not null default false,
  add column if not exists sales_visit_count integer not null default 0,
  add column if not exists sales_max_scroll_pct smallint not null default 0,
  add column if not exists sales_pricing_viewed boolean not null default false,
  add column if not exists sales_guarantee_viewed boolean not null default false,
  add column if not exists checkout_clicked boolean not null default false,
  add column if not exists checkout_click_count integer not null default 0,
  add column if not exists checkout_view_count integer not null default 0,
  add column if not exists checkout_engaged boolean not null default false,
  add column if not exists checkout_last_plan text,
  add column if not exists checkout_last_payment_mode text,
  add column if not exists checkout_last_button text,
  add column if not exists checkout_last_route text,
  add column if not exists checkout_last_clicked_at timestamptz,
  add column if not exists checkout_last_viewed_at timestamptz,
  add column if not exists last_intent_at timestamptz,
  add column if not exists stripe_customer_id text,
  add column if not exists stripe_checkout_session_id text,
  add column if not exists stripe_payment_intent_id text,
  add column if not exists stripe_subscription_schedule_id text,
  add column if not exists stripe_subscription_id text,
  add column if not exists payment_status text,
  add column if not exists initial_payment_cents integer,
  add column if not exists contractual_total_cents integer,
  add column if not exists paid_installment_count integer not null default 0,
  add column if not exists paid_total_cents integer not null default 0,
  add column if not exists purchased_at timestamptz,
  add column if not exists purchase_bonus_tag text,
  add column if not exists last_payment_at timestamptz,
  add column if not exists payment_failed_at timestamptz,
  add column if not exists last_presence_at timestamptz,
  add column if not exists last_event_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'mc2_registrations_purchase_bonus_tag_check'
      and conrelid = 'public.mc2_registrations'::regclass
  ) then
    alter table public.mc2_registrations
      add constraint mc2_registrations_purchase_bonus_tag_check
      check (
        purchase_bonus_tag is null
        or purchase_bonus_tag in ('avec_consultation_sonny', 'sans_consultation_sonny')
      ) not valid;
  end if;
end
$$;

alter table public.mc2_registrations
  validate constraint mc2_registrations_purchase_bonus_tag_check;

create index if not exists idx_mc2_registrations_purchase_bonus_tag
  on public.mc2_registrations (purchase_bonus_tag, purchased_at desc)
  where purchased_at is not null;

comment on column public.mc2_registrations.purchase_bonus_tag is
  'Statut figé lors du premier achat MC2 : avec_consultation_sonny avant CTA + 24 h, sinon sans_consultation_sonny.';

create unique index if not exists idx_mc2_registrations_stripe_checkout
  on public.mc2_registrations (stripe_checkout_session_id)
  where stripe_checkout_session_id is not null;

create unique index if not exists idx_mc2_registrations_stripe_schedule
  on public.mc2_registrations (stripe_subscription_schedule_id)
  where stripe_subscription_schedule_id is not null;

create table if not exists public.mc2_presence (
  token text primary key references public.mc2_registrations(token) on delete cascade,
  stage text not null default 'waiting' check (stage in ('waiting', 'session', 'replay')),
  current_second integer not null default 0,
  is_playing boolean not null default false,
  mode text not null default 'real' check (mode in ('real', 'test')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_mc2_presence_stage_updated
  on public.mc2_presence (stage, updated_at desc);

alter table public.mc2_presence enable row level security;

create table if not exists public.mc2_funnel_events (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token) on delete cascade,
  event_name text not null,
  event_value text,
  page_path text,
  metadata jsonb not null default '{}'::jsonb,
  dedupe_key text,
  occurred_at timestamptz not null default now()
);

create index if not exists idx_mc2_funnel_events_token_time
  on public.mc2_funnel_events (token, occurred_at desc);

create index if not exists idx_mc2_funnel_events_name_time
  on public.mc2_funnel_events (event_name, occurred_at desc);

create unique index if not exists idx_mc2_funnel_events_dedupe
  on public.mc2_funnel_events (token, dedupe_key)
  where dedupe_key is not null;

alter table public.mc2_funnel_events enable row level security;

comment on table public.mc2_presence is
  'Dernier signal de présence par prospect MC2.';

comment on table public.mc2_funnel_events is
  'Historique comportemental individuel du funnel MC2.';

create table if not exists public.mc2_stripe_webhook_events (
  event_id text primary key,
  event_type text not null,
  livemode boolean not null,
  processed_at timestamptz not null default now()
);

create index if not exists idx_mc2_stripe_events_time
  on public.mc2_stripe_webhook_events (processed_at desc);

alter table public.mc2_stripe_webhook_events enable row level security;

comment on table public.mc2_stripe_webhook_events is
  'Déduplication des webhooks Stripe du funnel MC2 uniquement.';
