-- Récupération des échéances Stripe du funnel MC2.
-- À exécuter une fois dans l’éditeur SQL Supabase avant d’activer
-- MC2_DUNNING_ENABLED. Aucun objet du funnel historique n’est modifié.

alter table public.mc2_registrations
  add column if not exists payment_retry_count integer not null default 0,
  add column if not exists payment_next_retry_at timestamptz,
  add column if not exists payment_failure_code text,
  add column if not exists payment_failure_message text,
  add column if not exists payment_recovered_at timestamptz,
  add column if not exists payment_exhausted_at timestamptz;

create table if not exists public.mc2_payment_recoveries (
  stripe_invoice_id text primary key,
  token text not null references public.mc2_registrations(token) on delete cascade,
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_payment_intent_id text,
  status text not null default 'failed'
    check (status in (
      'failed',
      'retry_scheduled',
      'payment_action_required',
      'recovered',
      'exhausted'
    )),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  retry_count integer not null default 0 check (retry_count >= 0),
  amount_due_cents integer not null default 0 check (amount_due_cents >= 0),
  currency text not null default 'eur',
  failure_code text,
  decline_code text,
  failure_message text,
  next_retry_at timestamptz,
  first_failed_at timestamptz,
  last_failed_at timestamptz,
  recovered_at timestamptz,
  exhausted_at timestamptz,
  last_stripe_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_mc2_payment_recoveries_token
  on public.mc2_payment_recoveries (token, updated_at desc);

create index if not exists idx_mc2_payment_recoveries_status
  on public.mc2_payment_recoveries (status, next_retry_at);

create table if not exists public.mc2_dunning_jobs (
  id bigint generated by default as identity primary key,
  token text not null references public.mc2_registrations(token) on delete cascade,
  stripe_invoice_id text,
  job_key text not null unique,
  message_type text not null
    check (message_type in (
      'payment_failed',
      'payment_action_required',
      'payment_final_failed',
      'payment_recovered_cleanup'
    )),
  dunning_stage integer not null default 0 check (dunning_stage between 0 and 6),
  due_at timestamptz not null default now(),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'sent', 'cancelled', 'skipped')),
  attempts integer not null default 0,
  mailerlite_group_id text,
  mailerlite_subscriber_id text,
  provider_response jsonb not null default '{}'::jsonb,
  last_error text,
  skip_reason text,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_mc2_dunning_jobs_due
  on public.mc2_dunning_jobs (status, due_at)
  where status in ('pending', 'retry');

create index if not exists idx_mc2_dunning_jobs_token
  on public.mc2_dunning_jobs (token, created_at desc);

create index if not exists idx_mc2_dunning_jobs_invoice
  on public.mc2_dunning_jobs (stripe_invoice_id, created_at desc)
  where stripe_invoice_id is not null;

create or replace function public.set_mc2_payment_recovery_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tr_mc2_payment_recoveries_updated_at
  on public.mc2_payment_recoveries;
create trigger tr_mc2_payment_recoveries_updated_at
  before update on public.mc2_payment_recoveries
  for each row execute function public.set_mc2_payment_recovery_updated_at();

drop trigger if exists tr_mc2_dunning_jobs_updated_at
  on public.mc2_dunning_jobs;
create trigger tr_mc2_dunning_jobs_updated_at
  before update on public.mc2_dunning_jobs
  for each row execute function public.set_mc2_payment_recovery_updated_at();

alter table public.mc2_payment_recoveries enable row level security;
alter table public.mc2_dunning_jobs enable row level security;

comment on table public.mc2_payment_recoveries is
  'État courant de récupération de chaque facture Stripe MC2.';

comment on table public.mc2_dunning_jobs is
  'File idempotente des notifications MailerLite liées aux impayés MC2.';
