-- Tracking comportemental individuel du funnel ES2 — migration additive.
-- À exécuter une fois dans Supabase SQL Editor AVANT de déployer le code associé.
-- Aucun champ existant n'est supprimé ou renommé.

alter table public.webinaire_registrations
  add column if not exists pdv_seconds integer not null default 0,
  add column if not exists sales_visit_count integer not null default 0,
  add column if not exists sales_max_scroll_pct smallint not null default 0,
  add column if not exists sales_pricing_viewed boolean not null default false,
  add column if not exists sales_guarantee_viewed boolean not null default false,
  add column if not exists checkout_clicked boolean not null default false,
  add column if not exists checkout_click_count integer not null default 0,
  add column if not exists checkout_view_count integer not null default 0,
  add column if not exists checkout_engaged boolean not null default false,
  add column if not exists checkout_last_plan text,
  add column if not exists checkout_last_payment_mode text,
  add column if not exists checkout_last_button text,
  add column if not exists checkout_last_route text,
  add column if not exists checkout_last_clicked_at timestamptz,
  add column if not exists checkout_last_viewed_at timestamptz,
  add column if not exists last_intent_at timestamptz;

create table if not exists public.webinaire_funnel_events (
  id bigint generated by default as identity primary key,
  token text not null references public.webinaire_registrations(token) on delete cascade,
  event_name text not null,
  occurred_at timestamptz not null default now(),
  page_path text,
  metadata jsonb not null default '{}'::jsonb,
  dedupe_key text
);

create index if not exists idx_webinaire_funnel_events_token_time
  on public.webinaire_funnel_events (token, occurred_at desc);

create index if not exists idx_webinaire_funnel_events_name_time
  on public.webinaire_funnel_events (event_name, occurred_at desc);

create unique index if not exists idx_webinaire_funnel_events_dedupe
  on public.webinaire_funnel_events (token, dedupe_key)
  where dedupe_key is not null;

alter table public.webinaire_funnel_events enable row level security;

comment on table public.webinaire_funnel_events is
  'Historique chronologique des comportements individuels du funnel ES2, relié au token webinaire.';

create or replace function public.record_webinaire_funnel_event(
  p_token text,
  p_event_name text,
  p_metadata jsonb default '{}'::jsonb,
  p_dedupe_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_inserted integer := 0;
  v_percent integer := 0;
  v_section text := '';
  v_plan text := null;
  v_payment text := null;
  v_button text := null;
  v_route text := null;
begin
  if p_token is null or length(trim(p_token)) = 0 then
    return jsonb_build_object('ok', false, 'error', 'token_missing');
  end if;

  if not exists (select 1 from public.webinaire_registrations where token = trim(p_token)) then
    return jsonb_build_object('ok', false, 'error', 'token_unknown');
  end if;

  insert into public.webinaire_funnel_events (
    token,
    event_name,
    occurred_at,
    page_path,
    metadata,
    dedupe_key
  ) values (
    trim(p_token),
    left(coalesce(p_event_name, ''), 64),
    v_now,
    nullif(left(coalesce(p_metadata->>'page_path', ''), 240), ''),
    coalesce(p_metadata, '{}'::jsonb),
    nullif(left(coalesce(p_dedupe_key, ''), 160), '')
  )
  on conflict do nothing;

  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then
    return jsonb_build_object('ok', true, 'duplicate', true);
  end if;

  if coalesce(p_metadata->>'percent', '') ~ '^[0-9]{1,3}$' then
    v_percent := least(100, greatest(0, (p_metadata->>'percent')::integer));
  end if;
  v_section := left(lower(coalesce(p_metadata->>'section', '')), 64);
  v_plan := case
    when lower(coalesce(p_metadata->>'plan', '')) in ('complet', 'avance', 'standard')
      then lower(p_metadata->>'plan')
    else null
  end;
  v_payment := case
    when lower(coalesce(p_metadata->>'payment_mode', '')) in ('1', '12')
      then lower(p_metadata->>'payment_mode')
    else null
  end;
  v_button := nullif(left(coalesce(p_metadata->>'button_id', ''), 100), '');
  v_route := nullif(left(coalesce(p_metadata->>'route', p_metadata->>'page_path', ''), 240), '');

  if p_event_name = 'invitation_visited' then
    update public.webinaire_registrations
      set visited_sales = true,
          sales_visit_count = coalesce(sales_visit_count, 0) + 1,
          last_intent_at = v_now,
          last_event_at = v_now
      where token = trim(p_token);
  elsif p_event_name = 'sales_scroll' then
    update public.webinaire_registrations
      set sales_max_scroll_pct = greatest(coalesce(sales_max_scroll_pct, 0), v_percent),
          last_intent_at = case when v_percent >= 50 then v_now else last_intent_at end,
          last_event_at = v_now
      where token = trim(p_token);
  elsif p_event_name = 'sales_section_viewed' then
    update public.webinaire_registrations
      set sales_pricing_viewed = coalesce(sales_pricing_viewed, false) or v_section = 'pricing',
          sales_guarantee_viewed = coalesce(sales_guarantee_viewed, false) or v_section = 'guarantee',
          last_intent_at = v_now,
          last_event_at = v_now
      where token = trim(p_token);
  elsif p_event_name = 'checkout_clicked' then
    update public.webinaire_registrations
      set checkout_clicked = true,
          clicked_cta = true,
          checkout_click_count = coalesce(checkout_click_count, 0) + 1,
          checkout_last_plan = coalesce(v_plan, checkout_last_plan),
          checkout_last_payment_mode = coalesce(v_payment, checkout_last_payment_mode),
          checkout_last_button = coalesce(v_button, checkout_last_button),
          checkout_last_route = coalesce(v_route, checkout_last_route),
          checkout_last_clicked_at = v_now,
          last_intent_at = v_now,
          last_event_at = v_now
      where token = trim(p_token);
  elsif p_event_name = 'checkout_viewed' then
    update public.webinaire_registrations
      set checkout_view_count = coalesce(checkout_view_count, 0) + 1,
          checkout_last_plan = coalesce(v_plan, checkout_last_plan),
          checkout_last_payment_mode = coalesce(v_payment, checkout_last_payment_mode),
          checkout_last_route = coalesce(v_route, checkout_last_route),
          checkout_last_viewed_at = v_now,
          last_intent_at = v_now,
          last_event_at = v_now
      where token = trim(p_token);
  elsif p_event_name = 'checkout_engaged' then
    update public.webinaire_registrations
      set checkout_engaged = true,
          checkout_last_plan = coalesce(v_plan, checkout_last_plan),
          checkout_last_payment_mode = coalesce(v_payment, checkout_last_payment_mode),
          checkout_last_route = coalesce(v_route, checkout_last_route),
          last_intent_at = v_now,
          last_event_at = v_now
      where token = trim(p_token);
  else
    update public.webinaire_registrations
      set last_event_at = v_now
      where token = trim(p_token);
  end if;

  return jsonb_build_object('ok', true, 'duplicate', false, 'occurred_at', v_now);
end;
$$;

revoke all on function public.record_webinaire_funnel_event(text, text, jsonb, text)
  from public, anon, authenticated;
grant execute on function public.record_webinaire_funnel_event(text, text, jsonb, text)
  to service_role;
